env:
  CIRRUS_CLONE_DEPTH: "1"

freebsd_instance:
  image_family: freebsd-12-1-snap

task:
  install_script: |
    pkg install -y git go
    GOBIN=$PWD/bin go get golang.org/dl/go1.17
    bin/go1.17 download
  build_script: bin/go1.17 build ./...
  test_script: bin/go1.17 test -race ./...
